// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	RequestingUserId string                 `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	UsersLimit       int32                  `protobuf:"varint,3,opt,name=users_limit,json=usersLimit,proto3" json:"users_limit,omitempty"`
	PostsLimit       int32                  `protobuf:"varint,4,opt,name=posts_limit,json=postsLimit,proto3" json:"posts_limit,omitempty"`
	UsersCursor      string                 `protobuf:"bytes,5,opt,name=users_cursor,json=usersCursor,proto3" json:"users_cursor,omitempty"`
	PostsCursor      string                 `protobuf:"bytes,6,opt,name=posts_cursor,json=postsCursor,proto3" json:"posts_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetRequestingUserId() string {
	if x != nil {
		return x.RequestingUserId
	}
	return ""
}

func (x *SearchRequest) GetUsersLimit() int32 {
	if x != nil {
		return x.UsersLimit
	}
	return 0
}

func (x *SearchRequest) GetPostsLimit() int32 {
	if x != nil {
		return x.PostsLimit
	}
	return 0
}

func (x *SearchRequest) GetUsersCursor() string {
	if x != nil {
		return x.UsersCursor
	}
	return ""
}

func (x *SearchRequest) GetPostsCursor() string {
	if x != nil {
		return x.PostsCursor
	}
	return ""
}

type SearchUserHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserHit) Reset() {
	*x = SearchUserHit{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserHit) ProtoMessage() {}

func (x *SearchUserHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserHit.ProtoReflect.Descriptor instead.
func (*SearchUserHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUserHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchUserHit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchUserHit) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *SearchUserHit) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type SearchPostHit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug           string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	ContentPreview string                 `protobuf:"bytes,5,opt,name=content_preview,json=contentPreview,proto3" json:"content_preview,omitempty"`
	Published      bool                   `protobuf:"varint,6,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchPostHit) Reset() {
	*x = SearchPostHit{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostHit) ProtoMessage() {}

func (x *SearchPostHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostHit.ProtoReflect.Descriptor instead.
func (*SearchPostHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPostHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchPostHit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchPostHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchPostHit) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchPostHit) GetContentPreview() string {
	if x != nil {
		return x.ContentPreview
	}
	return ""
}

func (x *SearchPostHit) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Users           []*SearchUserHit       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Posts           []*SearchPostHit       `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	UsersNextCursor string                 `protobuf:"bytes,3,opt,name=users_next_cursor,json=usersNextCursor,proto3" json:"users_next_cursor,omitempty"`
	PostsNextCursor string                 `protobuf:"bytes,4,opt,name=posts_next_cursor,json=postsNextCursor,proto3" json:"posts_next_cursor,omitempty"`
	UsersPartial    bool                   `protobuf:"varint,5,opt,name=users_partial,json=usersPartial,proto3" json:"users_partial,omitempty"`
	PostsPartial    bool                   `protobuf:"varint,6,opt,name=posts_partial,json=postsPartial,proto3" json:"posts_partial,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetUsers() []*SearchUserHit {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchResponse) GetPosts() []*SearchPostHit {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchResponse) GetUsersNextCursor() string {
	if x != nil {
		return x.UsersNextCursor
	}
	return ""
}

func (x *SearchResponse) GetPostsNextCursor() string {
	if x != nil {
		return x.PostsNextCursor
	}
	return ""
}

func (x *SearchResponse) GetUsersPartial() bool {
	if x != nil {
		return x.UsersPartial
	}
	return false
}

func (x *SearchResponse) GetPostsPartial() bool {
	if x != nil {
		return x.PostsPartial
	}
	return false
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xdb\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tR\x10requestingUserId\x12\x1f\n" +
	"\vusers_limit\x18\x03 \x01(\x05R\n" +
	"usersLimit\x12\x1f\n" +
	"\vposts_limit\x18\x04 \x01(\x05R\n" +
	"postsLimit\x12!\n" +
	"\fusers_cursor\x18\x05 \x01(\tR\vusersCursor\x12!\n" +
	"\fposts_cursor\x18\x06 \x01(\tR\vpostsCursor\"_\n" +
	"\rSearchUserHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\"\xa9\x01\n" +
	"\rSearchPostHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12'\n" +
	"\x0fcontent_preview\x18\x05 \x01(\tR\x0econtentPreview\x12\x1c\n" +
	"\tpublished\x18\x06 \x01(\bR\tpublished\"\x92\x02\n" +
	"\x0eSearchResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.search.v1.SearchUserHitR\x05users\x12.\n" +
	"\x05posts\x18\x02 \x03(\v2\x18.search.v1.SearchPostHitR\x05posts\x12*\n" +
	"\x11users_next_cursor\x18\x03 \x01(\tR\x0fusersNextCursor\x12*\n" +
	"\x11posts_next_cursor\x18\x04 \x01(\tR\x0fpostsNextCursor\x12#\n" +
	"\rusers_partial\x18\x05 \x01(\bR\fusersPartial\x12#\n" +
	"\rposts_partial\x18\x06 \x01(\bR\fpostsPartial2\x8d\x01\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBAZ?github.com/nikitashilov/microblog_grpc/proto/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: search.v1.SearchRequest
	(*SearchUserHit)(nil),  // 1: search.v1.SearchUserHit
	(*SearchPostHit)(nil),  // 2: search.v1.SearchPostHit
	(*SearchResponse)(nil), // 3: search.v1.SearchResponse
	(*emptypb.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_search_v1_search_proto_depIdxs = []int32{
	1, // 0: search.v1.SearchResponse.users:type_name -> search.v1.SearchUserHit
	2, // 1: search.v1.SearchResponse.posts:type_name -> search.v1.SearchPostHit
	0, // 2: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	4, // 3: search.v1.SearchService.HealthCheck:input_type -> google.protobuf.Empty
	3, // 4: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	4, // 5: search.v1.SearchService.HealthCheck:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
